spring:
 application:
  name: card-service
 datasource:
  #url: jdbc:mysql://localhost:3306/card_db
  url: jdbc:mysql://host.docker.internal:3306/card_db
  username: root
  password: aritraeshita
 jpa:
  hibernate:
   ddl-auto: update
   show-sql: true
   dialect: org.hibernate.dialect.MySQLDialect
server:
 port: 7071
 servlet:
  context-path: /card-service
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:7075/eureka/
      #defaultZone: http://localhost:7075/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    #ip-address: localhost
logging:
  level: 
    root: INFO

 
