spring:
 application:
  name: card-service
 datasource:
  url: jdbc:mysql://localhost:3306/card_db
  username: root
  password: aritraeshita
 jpa:
  hibernate:
   ddl-auto: update
   show-sql: true
   dialect: org.hibernate.dialect.MySQLDialect
 server:
  port: 7071
  servlet:
   context-path: /card-service
 
