spring:
 application:
  name: gateway
 cloud:
  gateway:
    discovery:
     locator:
      enabled: false
      lower-case-service-id: true
    httpclient:
      connect-timeout: 5000
      response-timeout: 2s
 security:
   oauth2:
     resourceserver:
       jwt:
         jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
 resilience4j:
   circuitbreaker:
     config:
       default:
         registerHealthIndicator: true
         slidingWindowSize: 6
         permittedNumberOfCallsInHalfOpenState: 2
         waitDurationInOpenState: 10s
         failureRateThreshold: 50
     instances:
      accountServiceCircuitBreaker:
        baseConfig: default
   retry:
    instances:
      accountServiceCircuitBreaker:
        maxAttempts: 4
        waitDuration: 1s
        exponentialBackoff:
          enabled: true
          multiplier: 2
          maxWaitDuration: 5s
        retryExceptions:
          - java.lang.Exception
        ignoreExceptions:
          - java.lang.IllegalArgumentException

        
 management:
  endpoints:
   web:
    exposure:
     include: "*"
  endpoint:
   gateway:
    enabled: true
 info:
  app:
   name: "Gateway"
   description: "Gateway server"
   version: "v1"   
server:
 port: 7077 
eureka:
  client:
    service-url:
      #defaultZone: http://eurekaserver:7075/eureka/
      defaultZone: http://localhost:7075/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost
logging:
  level: 
    root: INFO
