spring:
 application:
  name: gateway
server:
 port: 7077
 servlet:
  context-path: /gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7075/eureka/
      #defaultZone: http://eurekaserver:7075/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
logging:
  level: 
    root: DEBUG

 
