spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/(?<remaining>.*), /accounts/${remaining}
        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/card-service/**
          filters:
            - RewritePath=/card-service/(?<remaining>.*), /card-service/${remaining}
