spring:
 application:
  name: gateway   
server:
 port: 7077 
eureka:
  client:
    service-url:
      #defaultZone: http://eurekaserver:7075/eureka/
      defaultZone: http://localhost:7075/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost
logging:
  level: 
    root: DEBUG
