spring:
 application:
  name: gateway
 cloud:
  gateway:
    discovery:
     locator:
      enabled: false
      lower-case-service-id: true
    httpclient:
      connect-timeout: 5000
      response-timeout: 2s
 resilience4j:
   circuitbreaker:
     instances:
       cardServiceCircuitBreaker:
         registerHealthIndicator: true
         slidingWindowSize: 5
         permittedNumberOfCallsInHalfOpenState: 2
         waitDurationInOpenState: 10s
         failureRateThreshold: 50     
 management:
  endpoints:
   web:
    exposure:
     include: "*"
  endpoint:
   gateway:
    enabled: true
 info:
  app:
   name: "Gateway"
   description: "Gateway server"
   version: "v1"   
server:
 port: 7077 
eureka:
  client:
    service-url:
      #defaultZone: http://eurekaserver:7075/eureka/
      defaultZone: http://localhost:7075/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost
logging:
  level: 
    root: DEBUG
